import express from 'express';
import { addBook, deleteBook, editBook, findBook } from '../controllers/book.controller.js';
const router = express.Router();
router.post('/add-book', addBook);
router.post('/edit-book', editBook);
router.post('/find-book', findBook);
router.post('/saved-books-user',);
router.post('/borrowed-books-user',);
router.post('/borrowed-books',);
router.delete('/delete-book', deleteBook);
export default router;